/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;
import java.math.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import static newpackage.NewClass.getConnection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import static newpackage.Validation.Addressvalidation;
import static newpackage.Validation.LICENCEvalidation;
import static newpackage.Validation.NICvalidation;
import static newpackage.Validation.Namevalidation;
import static newpackage.Validation.Phonevalidation;



/**
 *
 * @author Krishan
 */
public class Customer extends javax.swing.JFrame {

    
    private static Customer obj=null;
    public static  Customer getObj() throws SQLException
    { 
        if(obj==null){ 
            obj=new  Customer();
        
           }return obj; 
          }


    /**
     * 
     */
   Connection connection=null;
            
    public Customer() throws SQLException {
        
       connection =getConnection();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonLoad = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        Designation = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        txtSEARCH = new javax.swing.JTextField();
        txtCheck = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jCID = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        txtLc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnGRVN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnUPDATE = new javax.swing.JButton();
        btnINSERT = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 750, 325));

        jButtonLoad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/clock.png"))); // NOI18N
        jButtonLoad.setText("Load");
        jButtonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, -1));

        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/cloud-error.png"))); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("NIC");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("DESIGNATION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 176, -1, -1));
        jLabel2.getAccessibleContext().setAccessibleName("Designation");
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        txtNIC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNIC.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtNICInputMethodTextChanged(evt);
            }
        });
        txtNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNICActionPerformed(evt);
            }
        });
        getContentPane().add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 173, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("FName");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 211, -1, -1));

        txtFname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 174, -1));

        Designation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Designation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MS", "MRS", "MR" }));
        Designation.setSelectedIndex(2);
        Designation.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DesignationComponentShown(evt);
            }
        });
        Designation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DesignationItemStateChanged(evt);
            }
        });
        Designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesignationActionPerformed(evt);
            }
        });
        Designation.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                DesignationAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(Designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 60, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("LName");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 305, -1, -1));

        txtLname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 173, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("ContactNo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 412, -1, 20));

        txtContactNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNoActionPerformed(evt);
            }
        });
        getContentPane().add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 173, -1));
        getContentPane().add(txtSEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 22, 372, -1));

        txtCheck.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/cloud-check.png"))); // NOI18N
        txtCheck.setText("Check");
        txtCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckActionPerformed(evt);
            }
        });
        getContentPane().add(txtCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 113, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jCID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCID.setText("ID");
        getContentPane().add(jCID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 30, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 443, 40, 30));

        txtLc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtLc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLcActionPerformed(evt);
            }
        });
        getContentPane().add(txtLc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 173, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Licence#");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 356, -1, 20));

        txtAddress1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 173, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        btnGRVN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGRVN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/open-letter.png"))); // NOI18N
        btnGRVN.setText("Go Revervation");
        btnGRVN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGRVNActionPerformed(evt);
            }
        });
        getContentPane().add(btnGRVN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 253, 40));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/eye.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(982, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 60));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/cloud-error.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUPDATE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/cloud-up.png"))); // NOI18N
        btnUPDATE.setText("UPDATE");
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });

        btnINSERT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnINSERT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/bookmark.png"))); // NOI18N
        btnINSERT.setText("INSERT");
        btnINSERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnINSERTActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/train.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnINSERT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 573, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnUPDATE)
                            .addComponent(btnINSERT))))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1100, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/background-polygon-lightblue.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1100, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
                 
        jTable1.setModel(new DefaultTableModel(null,new String[]{}));
        txtNIC.setText("");
        jCID.setText("");
        txtFname.setText("");
         txtLname.setText("");
          txtContactNo.setText("");
          txtAddress1.setText("");
          txtLc.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadActionPerformed

      
      
        
        ShowCustomerDatabase();
    }//GEN-LAST:event_jButtonLoadActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        SearchJtable();
       
       
    }//GEN-LAST:event_btnSearchActionPerformed

    private void DesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesignationActionPerformed

    private void DesignationAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_DesignationAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_DesignationAncestorAdded

    private void DesignationComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DesignationComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_DesignationComponentShown

    private void DesignationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DesignationItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_DesignationItemStateChanged

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNoActionPerformed

    private void btnINSERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnINSERTActionPerformed
        if(NICvalidation(txtNIC.getText()) && Namevalidation(txtFname.getText()) && Namevalidation(txtLname.getText()) && LICENCEvalidation(txtLc.getText()) && Phonevalidation(txtContactNo.getText()) && Addressvalidation(txtAddress1.getText()))
        {
            InsertCustomerDatabase();
        }
        
    }//GEN-LAST:event_btnINSERTActionPerformed

    private void txtCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckActionPerformed
        Check();
    }//GEN-LAST:event_txtCheckActionPerformed

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
        if( Namevalidation(txtFname.getText()) && Namevalidation(txtLname.getText()) && LICENCEvalidation(txtLc.getText()) && Phonevalidation(txtContactNo.getText()) && Addressvalidation(txtAddress1.getText()))
        {
           UPDATECustomerDatabase();
        }
    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int r=jTable1.getSelectedRow();
        jCID.setText(jTable1.getValueAt(r, 0).toString());
        txtNIC.setText((String) jTable1.getValueAt(r, 1));
        txtFname.setText((String) jTable1.getValueAt(r, 3));
         txtLname.setText((String) jTable1.getValueAt(r, 4));
        Designation.setSelectedItem((String) jTable1.getValueAt(r, 2));
        txtContactNo.setText((String) jTable1.getValueAt(r, 5));
        txtAddress1.setText((String) jTable1.getValueAt(r, 6));
        txtLc.setText((String) jTable1.getValueAt(r, 7));
         
         
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         int ReqCancel=JOptionPane.showConfirmDialog(null, "Are You Sure ? ");
         if(ReqCancel==0)
        {
        DELETECustomerDatabase();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICActionPerformed

    private void txtLcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLcActionPerformed

    private void txtAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress1ActionPerformed

    private void btnGRVNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGRVNActionPerformed
        
        Reserve rv ;
       try {
           String Rcid=JOptionPane.showInputDialog("Input Customer ID");
           rv = new Reserve(Rcid);
           if(Rcid!=null)
           {
                rv.setVisible(true);
               
            } 
              
            
       } catch (SQLException ex) {
           Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }//GEN-LAST:event_btnGRVNActionPerformed

    private void txtNICInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtNICInputMethodTextChanged
           

    }//GEN-LAST:event_txtNICInputMethodTextChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose()  ;
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
   
 
    
      public  void ShowCustomerDatabase() {
      
            
     
            // Create and execute a SELECT SQL statement.
            String selectSql = "SELECT * " + "FROM customer ";

            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery(selectSql)) {

              
      
                jTable1.setModel(DbUtils.resultSetToTableModel(resultSet));
              
            }
        
        catch (Exception e) {
               JOptionPane.showMessageDialog(null,"Error");

        }
    
    }
      
      
      
      
      /*Search*/
      public  void SearchJtable() {
      
           
            
           
            // Create and execute a SELECT SQL statement.
            String selectSql = "SELECT * " + "FROM customer "+ "WHERE FName LIKE '%"+txtSEARCH.getText()+"%' OR LName LIKE '%"+txtSEARCH.getText()+"%'"  + "OR NIC LIKE '%"+txtSEARCH.getText()+"%'" + "OR CID LIKE '%"+txtSEARCH.getText()+"%'"   ;

            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery(selectSql)) {
                
                

              
              jTable1.setModel(DbUtils.resultSetToTableModel(resultSet));
              
         
                
                
            }
        
        catch (Exception e) {
              JOptionPane.showMessageDialog(null,"Error");

        }
    
      
      
      
      }
    
    
    
    
    
    
    public  void InsertCustomerDatabase() {
            
         
            // Prepared statement to insert data
                String insertSql = "INSERT INTO Customer (NIC, Designation,FName,LName,Contact_No,Address,LicenceNum ) VALUES (?,?,?,?,?,?,?);";

               
                try (PreparedStatement prep = connection.prepareStatement(insertSql)) {
                        prep.setString(1, txtNIC.getText().toUpperCase());
                    
                        prep.setString(2, Designation.getSelectedItem().toString());
                        prep.setString(3, txtFname.getText().toUpperCase());
                        prep.setString(4, txtLname.getText().toUpperCase());
                        prep.setString(5, txtContactNo.getText());
                         prep.setString(6, txtAddress1.getText().toUpperCase());
                          prep.setString(7, txtLc.getText().toUpperCase());

                         prep.executeUpdate();
                        JOptionPane.showMessageDialog(null,"Insert Complete");
        }
        catch (Exception e) {
              JOptionPane.showMessageDialog(null,"This data already in database");

           
        }
    
    }
    
    
    public  void Check() {
    
     
            // Create and execute a SELECT SQL statement.
            String selectSql = "SELECT * " + "FROM customer " + "WHERE NIC='"+txtNIC.getText()+"'" ;

            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery(selectSql)) {

                
                
             
                if (resultSet.next())
                {
                        
                      jCID.setText(resultSet.getString(1));
                     txtNIC.setText(resultSet.getString(2));
                     Designation.setSelectedItem(resultSet.getString(3)) ;
                     txtFname.setText(resultSet.getString(4));
                     txtLname.setText(resultSet.getString(5));
                     txtContactNo.setText(resultSet.getString(6));
                   txtAddress1.setText(resultSet.getString(7));
                   txtLc.setText(resultSet.getString(8));
                }
                else{
                    JOptionPane.showMessageDialog(null,"This NIC not in database");
                
                }
               
            }
        
        catch (Exception e) {
                   JOptionPane.showMessageDialog(null,"Error");

        }
        
       
        
    }
    
    
    
    
    
    
    
    public  void UPDATECustomerDatabase() {
            
         
            // Prepared statement to insert data
                String updateSql = "UPDATE customer " + "SET Designation=? ,FName=? ,LName=?, Contact_No=?,Address=?,LicenceNum=? "+  "WHERE NIC=? ;";

               
                try (PreparedStatement prep = connection.prepareStatement(updateSql)) {
                      
                    
                        prep.setString(1, Designation.getSelectedItem().toString());
                        prep.setString(2, txtFname.getText().toUpperCase());
                        prep.setString(3, txtLname.getText().toUpperCase());
                        prep.setString(4, txtContactNo.getText());
                         prep.setString(7, txtNIC.getText());
                         prep.setString(5, txtAddress1.getText().toUpperCase());
                          prep.setString(6, txtLc.getText());
                        
                        
                       int i =    prep.executeUpdate();
                        
                if(i>0){
               
                    JOptionPane.showMessageDialog(null,"Update Complete!");
                
                     }
                 else{
                     JOptionPane.showMessageDialog(null,"This NIC not in database");
                     }
                        
                        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error ");
            
        }
    
    }
    
    
    
    
    
    
    
    
    
    
    public  void DELETECustomerDatabase() {
            
         
            // Prepared statement to insert data
                String updateSql = "DELETE customer " +  "WHERE NIC=? ;";

               
                try (PreparedStatement prep = connection.prepareStatement(updateSql)) {
                      
                    
                         prep.setString(1, txtNIC.getText());
                        
                        
                        
                         prep.executeUpdate();
                        JOptionPane.showMessageDialog(null,"Successful!");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Its not in database");
            
        }
    
    }
    
    
    
    
    
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Customer().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Designation;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGRVN;
    private javax.swing.JButton btnINSERT;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonLoad;
    private javax.swing.JLabel jCID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JButton txtCheck;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLc;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtSEARCH;
    // End of variables declaration//GEN-END:variables
}
