/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import static newpackage.IReport.PaymentReport;

/**
 *
 * @author Krishan
 */
public class MAIN_MENU extends javax.swing.JFrame {

    /**
     * Creates new form MAIN_MENU
     */
    public MAIN_MENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCustomer_Reservation = new javax.swing.JButton();
        btnVehicleReturned = new javax.swing.JButton();
        btnVehicle_Driver = new javax.swing.JButton();
        btnDailyPayment_Report = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(596, 680));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCustomer_Reservation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCustomer_Reservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/briefcase.png"))); // NOI18N
        btnCustomer_Reservation.setText("Customer_Reservation");
        btnCustomer_Reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomer_ReservationActionPerformed(evt);
            }
        });
        getContentPane().add(btnCustomer_Reservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 241, -1, 80));

        btnVehicleReturned.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVehicleReturned.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/car.png"))); // NOI18N
        btnVehicleReturned.setText("Vehicle Returned");
        btnVehicleReturned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicleReturnedActionPerformed(evt);
            }
        });
        getContentPane().add(btnVehicleReturned, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 210, 80));

        btnVehicle_Driver.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVehicle_Driver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/store.png"))); // NOI18N
        btnVehicle_Driver.setText("Vehicle_Driver");
        btnVehicle_Driver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicle_DriverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVehicle_Driver, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 210, 80));

        btnDailyPayment_Report.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDailyPayment_Report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/bill.png"))); // NOI18N
        btnDailyPayment_Report.setText("Daily Payment Report");
        btnDailyPayment_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDailyPayment_ReportActionPerformed(evt);
            }
        });
        getContentPane().add(btnDailyPayment_Report, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 210, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/g11.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 620, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/pup.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 70, 270));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/pdwn.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, 270));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/background-polygon-lightblue.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 660, 590));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 660, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomer_ReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomer_ReservationActionPerformed
        try {
            
            Customer.getObj().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MAIN_MENU.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCustomer_ReservationActionPerformed

    private void btnVehicleReturnedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicleReturnedActionPerformed
       
        try {
            Returned.getObj().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MAIN_MENU.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVehicleReturnedActionPerformed

    private void btnVehicle_DriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicle_DriverActionPerformed
          try {
            
            Vehicle.getObj().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVehicle_DriverActionPerformed

    private void btnDailyPayment_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDailyPayment_ReportActionPerformed
          HashMap param= new HashMap();
         Date D=new Date();
         SimpleDateFormat year=new SimpleDateFormat("yyyy");
          SimpleDateFormat month=new SimpleDateFormat("MM");
           SimpleDateFormat day=new SimpleDateFormat("dd");
        
           System.out.print(Integer.parseInt(month.format(D)));
                 
         String report="E:\\SLIIT 2d year\\ST2\\graphical f\\JavaTest\\JavaTest\\src\\newpackage\\report\\report1.jasper";
        
         param.put("YEAR", Integer.parseInt(year.format(D)));
         param.put("MONTH", Integer.parseInt(month.format(D)));
         param.put("DAY",Integer.parseInt( day.format(D)));
         
      
        try {
            PaymentReport(report,param);
        } catch (SQLException | JRException ex) {
            Logger.getLogger(PayBILL.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDailyPayment_ReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN_MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer_Reservation;
    private javax.swing.JButton btnDailyPayment_Report;
    private javax.swing.JButton btnVehicleReturned;
    private javax.swing.JButton btnVehicle_Driver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
