/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import static newpackage.NewClass.getConnection;



/**
 *
 * @author Krishan
 */
public class Returned extends javax.swing.JFrame {
    
     private static Returned obj=null;
    public static  Returned getObj() throws SQLException
    { 
        if(obj==null){ 
            obj=new  Returned();
        
           }return obj; 
          }

    /**
     * Creates new form Returned
     */
     
    public Returned() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnLoad = new javax.swing.JButton();
        jExtraDays = new javax.swing.JLabel();
        jPID = new javax.swing.JLabel();
        jVID = new javax.swing.JLabel();
        jExtraDays1 = new javax.swing.JLabel();
        jPID1 = new javax.swing.JLabel();
        jVID1 = new javax.swing.JLabel();
        btnPayment = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/train.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 56, 530, 270));

        btnLoad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/clock.png"))); // NOI18N
        btnLoad.setText("Load");
        btnLoad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, -1));

        jExtraDays.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jExtraDays.setText("0");
        getContentPane().add(jExtraDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 26, -1));

        jPID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPID.setText("0");
        getContentPane().add(jPID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 60, -1));

        jVID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jVID.setText("0");
        getContentPane().add(jVID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 60, -1));

        jExtraDays1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jExtraDays1.setText("Extra Days");
        getContentPane().add(jExtraDays1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jPID1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPID1.setText("PID");
        getContentPane().add(jPID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 26, -1));

        jVID1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jVID1.setText("VID");
        getContentPane().add(jVID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 33, -1));

        btnPayment.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/%.png"))); // NOI18N
        btnPayment.setText("Go Payment");
        btnPayment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });
        getContentPane().add(btnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 40));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 50));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 710, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/background-polygon-lightblue.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 710, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     try{
        int r=jTable1.getSelectedRow();
     
        jPID.setText( jTable1.getValueAt(r, 3).toString());
        jExtraDays.setText(jTable1.getValueAt(r, 1).toString());
        jVID.setText( jTable1.getValueAt(r, 4).toString());
     }
     
     catch(NullPointerException e){
     }


    }//GEN-LAST:event_jTable1MouseClicked

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        try {
            ShowNotReturned();
        } catch (SQLException ex) {
            Logger.getLogger(Returned.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        try {
            Payment pay=new Payment(jVID.getText(),jExtraDays.getText(),jPID.getText());
            pay.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Returned.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       
    }//GEN-LAST:event_formWindowClosed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
     
    }//GEN-LAST:event_formWindowDeactivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose()  ;
    }//GEN-LAST:event_jButton2ActionPerformed

    
      public  void ShowNotReturned() throws SQLException{
      
            Connection connection =getConnection();
     
            // Create and execute a SELECT SQL statement.
            String selectSql = "SELECT ReservationID,DATEDIFF(DAY,ReturnDate,GETDATE()) as 'Extra Days',ReturnDate,PID,VID " +
                "FROM Reservation " +
                "WHERE DATEDIFF(DAY,ReturnDate,GETDATE())>=0 AND ReturnComplete='NO' AND PID IS NOT NULL";

            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery(selectSql)) {

              
      
                jTable1.setModel(DbUtils.resultSetToTableModel(resultSet));
              
            }
        
        catch (Exception e) {
           JOptionPane.showMessageDialog(null,"Error");
        }
    
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Returned.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Returned().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jExtraDays;
    private javax.swing.JLabel jExtraDays1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jPID;
    private javax.swing.JLabel jPID1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jVID;
    private javax.swing.JLabel jVID1;
    // End of variables declaration//GEN-END:variables
}
