package newpackage;


import java.awt.HeadlessException;
import java.sql.*;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import static newpackage.Validation.Colorvalidation;
import static newpackage.Validation.Costvalidation;
import static newpackage.Validation.DriverLICENCEvalidation;
import static newpackage.Validation.Namevalidation;
import static newpackage.Validation.Phonevalidation;
import static newpackage.Validation.VehicleModelvalidation;
import static newpackage.Validation.VehicleTypevalidation;
import static newpackage.Validation.isLCDateValid;
import static newpackage.Validation.isThisDateValid;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Vehicle extends javax.swing.JFrame {
    
    
    
     private static Vehicle obj=null;
    public static  Vehicle getObj() throws SQLException
      { 
        if(obj==null){ 
            obj=new  Vehicle();
        
           }return obj; 
          }
    
    Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;

    /**
     * Creates new form search_bar
     * @throws java.sql.SQLException
     */
    public Vehicle() throws SQLException {
        initComponents();
        conn = NewClass.getConnection();
        updatetab();
        jPanel2.setVisible(false);
        
    }
    private void updatetab(){
        try{
        String sql="select * from Vehicle";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        
         jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "no values");
           
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        validation1 = new newpackage.Validation();
        jPanel1 = new javax.swing.JPanel();
        btnCheck = new javax.swing.JButton();
        txtsrch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttyp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtReg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        CVehicleStatus = new javax.swing.JComboBox<>();
        jDriver = new javax.swing.JLabel();
        btnVupdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtDid = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtContactno = new javax.swing.JTextField();
        txtLicenno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtLicenexp = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtVehicleid = new javax.swing.JTextField();
        btnDinsert = new javax.swing.JButton();
        btnDupdate = new javax.swing.JButton();
        btnDrefresh = new javax.swing.JButton();
        btnDdelete = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggle = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/cloud-check.png"))); // NOI18N
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        jPanel1.add(btnCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, 40));

        txtsrch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsrchActionPerformed(evt);
            }
        });
        jPanel1.add(txtsrch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 11, 254, 37));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Search Car");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 146, 20));

        txtid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 90, 129, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txttyp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttypActionPerformed(evt);
            }
        });
        jPanel1.add(txttyp, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 206, 129, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Type");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 205, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Model");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Status");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        txtModel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 243, 129, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Driver");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/train.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 120, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/cloud-refresh.png"))); // NOI18N
        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 441, -1, 50));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/bookmark.png"))); // NOI18N
        jButton4.setText("insert");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 120, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Reg.No");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, -1, -1));

        txtReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegActionPerformed(evt);
            }
        });
        jPanel1.add(txtReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 136, 129, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Cost");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtCost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostActionPerformed(evt);
            }
        });
        jPanel1.add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 171, 129, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Color");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 284, -1, -1));

        txtColor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        jPanel1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 285, 129, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 552, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/cloud-error.png"))); // NOI18N
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 421, 110, 40));

        CVehicleStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        CVehicleStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CVehicleStatusItemStateChanged(evt);
            }
        });
        CVehicleStatus.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                CVehicleStatusAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        CVehicleStatus.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                CVehicleStatusComponentShown(evt);
            }
        });
        CVehicleStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVehicleStatusActionPerformed(evt);
            }
        });
        jPanel1.add(CVehicleStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 344, -1, -1));

        jDriver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jDriver.setText("DriverID");
        jPanel1.add(jDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 389, -1, -1));

        btnVupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/cloud-up.png"))); // NOI18N
        btnVupdate.setText("Update");
        btnVupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnVupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/background-polygon-lightblue.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 444, 520));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDidActionPerformed(evt);
            }
        });
        jPanel2.add(txtDid, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 50, 129, -1));

        txtDob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });
        jPanel2.add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 79, 129, -1));

        txtFname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        jPanel2.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 113, 129, -1));

        txtLname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });
        jPanel2.add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 147, 129, -1));

        txtContactno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtContactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 176, 129, -1));

        txtLicenno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLicenno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicennoActionPerformed(evt);
            }
        });
        jPanel2.add(txtLicenno, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 210, 129, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("DriverID");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("DOB");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 78, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("FName");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 111, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("LName");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 144, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("ContactNo");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 172, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("LicenseNo");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 205, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("LicenseExpiry");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 244, -1, -1));

        txtLicenexp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLicenexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenexpActionPerformed(evt);
            }
        });
        jPanel2.add(txtLicenexp, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 244, 129, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("VehicleID");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 285, -1, -1));

        txtVehicleid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtVehicleid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleidActionPerformed(evt);
            }
        });
        jPanel2.add(txtVehicleid, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 285, 129, -1));

        btnDinsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDinsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/bookmark.png"))); // NOI18N
        btnDinsert.setText("insert");
        btnDinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDinsertActionPerformed(evt);
            }
        });
        jPanel2.add(btnDinsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 120, -1));

        btnDupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/cloud-up.png"))); // NOI18N
        btnDupdate.setText("Update");
        btnDupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDupdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnDupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 120, -1));

        btnDrefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/cloud-refresh.png"))); // NOI18N
        btnDrefresh.setText("Refresh");
        btnDrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrefreshActionPerformed(evt);
            }
        });
        jPanel2.add(btnDrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 130, -1));

        btnDdelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/cloud-error.png"))); // NOI18N
        btnDdelete.setText("Delete");
        btnDdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDdeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 130, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/background-polygon-lightblue.jpg"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 450));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, -1, 450));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Type", "Modle", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 156, 475, 353));

        jToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/32/packman.png"))); // NOI18N
        jToggle.setText("Diver Details");
        jToggle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleStateChanged(evt);
            }
        });
        jToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleActionPerformed(evt);
            }
        });
        getContentPane().add(jToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 144, 51));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 40));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1490, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 1490, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images/background-polygon-lightblue.jpg"))); // NOI18N
        jLabel19.setText("jLabel19");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1490, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtsrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsrchActionPerformed
               
          // Create and execute a SELECT SQL statement.
            String selectSql = "SELECT * " + "FROM Vehicle "+ "WHERE RegistrationNo LIKE '%"+txtsrch.getText()+"%' OR Model LIKE '%"+txtsrch.getText()+"%'"  + "OR VType LIKE '%"+txtsrch.getText()+"%'" + "OR VStatus LIKE '%"+txtsrch.getText()+"%' "+ " OR Colour LIKE '%"+txtsrch.getText()+"%' "   ;

            try (Statement statement = conn.createStatement();
                 ResultSet resultSet = statement.executeQuery(selectSql)) {
                
                

              
              jTable1.setModel(DbUtils.resultSetToTableModel(resultSet));
              
         
                
                
            }
        
        catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_txtsrchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     dispose()  ;     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                updatetab();
               txtReg.setText(null);
                         
               txtCost.setText(null);
                             
               txtColor.setText(null);
               txtsrch.setText(null);
               txtid.setText(null);
                             
               txttyp.setText(null);
                              
               jDriver.setText(null);
                             
              
                           
               txtModel.setText(null);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
if( Colorvalidation(txtColor.getText()) && VehicleTypevalidation(txttyp.getText())  && VehicleModelvalidation(txtModel.getText()) && Costvalidation(txtCost.getText()) && !txtReg.getText().isEmpty() )
        {        // TODO add your handling code here:
                 
        try{
                       String sql="INSERT INTO Vehicle VALUES(?,?,?,?,?,?,?,'')";
           pst=conn.prepareStatement(sql);
           pst.setInt(1,Integer.parseInt(txtid.getText()));
           pst.setString(2,txtReg.getText().toUpperCase());
           pst.setInt(3,Integer.parseInt(txtCost.getText()));
           pst.setString(4,txttyp.getText().toUpperCase());
           pst.setString(6,txtColor.getText().toUpperCase());
        
           
           pst.setString(7,CVehicleStatus.getSelectedItem().toString());
           pst.setString(5,txtModel.getText().toUpperCase());
            
           int i=pst.executeUpdate();
         
           
           if(i>0){
               
                JOptionPane.showMessageDialog(null,"Insert Complete!");
                
               
               
           }
           else{
                JOptionPane.showMessageDialog(null,"wrong input");
           }
            
        }
        catch(SQLException | NumberFormatException | HeadlessException e){
            JOptionPane.showMessageDialog(null,"Vehicle Registration Number is already in database");
            
        }
     }  
      else{                   
        JOptionPane.showMessageDialog(null,"Vehicle Registration Number is Empty");
        
       }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegActionPerformed

    private void txtCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostActionPerformed

    private void txttypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttypActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttypActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         dispose();
               Customer s;
        try {
            s = new Customer();
            s.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Vehicle.class.getName()).log(Level.SEVERE, null, ex);
        }
               
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
                   
        try{
                       String sql="Delete from Vehicle where VehicleID=? ";
                               
           pst=conn.prepareStatement(sql);
           pst.setInt(1,Integer.parseInt(txtid.getText()));
          
          // rs=pst.executeQuery();
           int i=pst.executeUpdate();
         
           
           if(i>0){
               
                JOptionPane.showMessageDialog(null,"Deleted");
                
               //rs.close();
               
           }
           else{
                JOptionPane.showMessageDialog(null,"wrong input");
           }
            
        }
        catch(SQLException | NumberFormatException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void CVehicleStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CVehicleStatusItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CVehicleStatusItemStateChanged

    private void CVehicleStatusAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_CVehicleStatusAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_CVehicleStatusAncestorAdded

    private void CVehicleStatusComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_CVehicleStatusComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_CVehicleStatusComponentShown

    private void CVehicleStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVehicleStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CVehicleStatusActionPerformed

    private void btnVupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVupdateActionPerformed
         // TODO add your handling code here:
    if( Colorvalidation(txtColor.getText()) && VehicleTypevalidation(txttyp.getText())  && VehicleModelvalidation(txtModel.getText()) && Costvalidation(txtCost.getText()) && !txtReg.getText().isEmpty() )

     {        
        try{
                       String sql="UPDATE Vehicle SET RegistrationNo=? , CostPerDay=? , VType=? , Model=? , Colour=? , VStatus=? WHERE VehicleID=?";
           pst=conn.prepareStatement(sql);
           
           pst.setString(1,txtReg.getText().toUpperCase());
           pst.setInt(2,Integer.parseInt(txtCost.getText()));
           pst.setString(3,txttyp.getText().toUpperCase());
           pst.setString(5,txtColor.getText().toUpperCase());
           pst.setString(4,txtModel.getText().toUpperCase());
           
           pst.setString(6,CVehicleStatus.getSelectedItem().toString());
           pst.setInt(7,Integer.parseInt(txtid.getText()));
            
           int i=pst.executeUpdate();
         
           
           if(i>0){
               
                JOptionPane.showMessageDialog(null,"Update Complete!");
                
               
               
           }
           else{
                 JOptionPane.showMessageDialog(null,"VehicleID is not  in database");
           }
            
        }
        catch(SQLException | NumberFormatException | HeadlessException e){
            JOptionPane.showMessageDialog(null,"Vehicle Registration Number is already in database");
            
        }
     } 
    else{                   
        JOptionPane.showMessageDialog(null,"Vehicle Registration Number is Empty");
        
       }
    
    

    }//GEN-LAST:event_btnVupdateActionPerformed

    private void txtLicennoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicennoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicennoActionPerformed

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed

    private void txtDidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDidActionPerformed

    private void txtLicenexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenexpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenexpActionPerformed

    private void txtVehicleidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleidActionPerformed

    private void btnDinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDinsertActionPerformed

        if(  Namevalidation(txtFname.getText()) && Namevalidation(txtLname.getText()) && DriverLICENCEvalidation(txtLicenno.getText()) && Phonevalidation(txtContactno.getText()) && isThisDateValid(txtDob.getText()) && isLCDateValid(txtLicenexp.getText()) )
        {        
        
        
        
                 
        try{
                       String sql="INSERT INTO Driver VALUES(?,?,?,?,?,?,?,?)";
                       
                      
           pst=conn.prepareStatement(sql);
           pst.setInt(1,Integer.parseInt(txtDid.getText()));
           pst.setString(2,txtDob.getText());
           pst.setString(3,txtFname.getText().toUpperCase());
           pst.setString(4,txtLname.getText().toUpperCase());
           pst.setString(5,txtContactno.getText());
        
           
           pst.setString(6,txtLicenno.getText().toUpperCase());
           pst.setString(7,txtLicenexp.getText());
           pst.setInt(8,Integer.parseInt(txtVehicleid.getText()));
           int i=pst.executeUpdate();
         
           
           if(i>0){
               
                JOptionPane.showMessageDialog(null,"Submitted");
                
               
               
           }
           else{
                JOptionPane.showMessageDialog(null,"wrong input");
           }
            
        }
        catch(SQLException | NumberFormatException | HeadlessException e){
            if(txtVehicleid.getText().isEmpty())
                    {
                        JOptionPane.showMessageDialog(null,"VehicleID is Empty");
                    }
            else if(!txtLicenexp.getText().isEmpty() && !txtDob.getText().isEmpty() && !txtVehicleid.getText().isEmpty())
            {JOptionPane.showMessageDialog(null,"VehicleID is invalid");
            }
            else 
                    { JOptionPane.showMessageDialog(null,"Dob or Licence Exp invalid");

            }
        }
        
       }
                                    
        
        
    }//GEN-LAST:event_btnDinsertActionPerformed

    private void btnDupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDupdateActionPerformed
        
        
     
        if(  Namevalidation(txtFname.getText()) && Namevalidation(txtLname.getText()) && DriverLICENCEvalidation(txtLicenno.getText()) && Phonevalidation(txtContactno.getText()) && isThisDateValid(txtDob.getText()) && isLCDateValid(txtLicenexp.getText()) )
        {    
                 
        try{
                       String sql="UPDATE Driver SET DOB=? , FName=? , LName=? , ContactNo=? , LicenseNo=? , LicenseExpiry=? , VehicleID=? WHERE DriverID=? ";
                       
                      
           pst=conn.prepareStatement(sql);
          
           pst.setString(1,txtDob.getText());
           pst.setString(2,txtFname.getText().toUpperCase());
           pst.setString(3,txtLname.getText().toUpperCase());
           pst.setString(4,txtContactno.getText());
        
           
           pst.setString(5,txtLicenno.getText().toUpperCase());
           pst.setString(6,txtLicenexp.getText());
           pst.setInt(7,Integer.parseInt(txtVehicleid.getText()));
            pst.setInt(8,Integer.parseInt(txtDid.getText()));
           int i=pst.executeUpdate();
         
           
           if(i>0){
               
                JOptionPane.showMessageDialog(null,"Submitted");
                
               
               
           }
           else{
                JOptionPane.showMessageDialog(null,"wrong input");
           }
            
        }
        catch(SQLException | NumberFormatException | HeadlessException e){
            if(txtVehicleid.getText().isEmpty())
                    {
                        JOptionPane.showMessageDialog(null,"VehicleID is Empty");
                    }
            else if(!txtLicenexp.getText().isEmpty() && !txtDob.getText().isEmpty() && !txtVehicleid.getText().isEmpty())
            {JOptionPane.showMessageDialog(null,"VehicleID is invalid");
            }
            else{
                  JOptionPane.showMessageDialog(null,"Dob or Licence Exp invalid");

            }
        }
      }
    
                                    
        
        
        
    }//GEN-LAST:event_btnDupdateActionPerformed

    private void btnDrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrefreshActionPerformed
         try{
        String sql="select * from Driver";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
         jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "no values");
           
            
        }
        
    }//GEN-LAST:event_btnDrefreshActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int r=jTable1.getSelectedRow();
        txtDid.setText(jTable1.getValueAt(r, 0).toString());
        txtDob.setText( jTable1.getValueAt(r, 1).toString());
        txtFname.setText( jTable1.getValueAt(r, 2).toString());
         txtLname.setText( jTable1.getValueAt(r, 3).toString());
        txtContactno.setText( jTable1.getValueAt(r, 4).toString());
        txtLicenno.setText(jTable1.getValueAt(r, 5).toString());
        txtLicenexp.setText(jTable1.getValueAt(r, 6).toString());
        txtVehicleid.setText( jTable1.getValueAt(r, 7).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleActionPerformed
     
         if(jToggle.isSelected())
         {
             
            jPanel1.setVisible(false);
             jPanel2.setVisible(true);
             btnDrefresh.doClick();
             
             
              txtDid.setText(null);
        txtDob.setText( null);
        txtFname.setText( null);
         txtLname.setText( null);
        txtContactno.setText(null);
        txtLicenno.setText(null);
        txtLicenexp.setText(null);
        txtVehicleid.setText( null);
         }
         else
         {
            
                jPanel1.setVisible(true);
                jPanel2.setVisible(false);
                  jButton3.doClick();
         }
         
    }//GEN-LAST:event_jToggleActionPerformed

    private void jToggleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleStateChanged
        
    }//GEN-LAST:event_jToggleStateChanged

    private void btnDdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDdeleteActionPerformed
        try{
                       String sql="Delete from Driver where DriverID=? ";
                               
           pst=conn.prepareStatement(sql);
           pst.setInt(1,Integer.parseInt(txtDid.getText()));
          
          // rs=pst.executeQuery();
           int i=pst.executeUpdate();
         
           
           if(i>0){
               
                JOptionPane.showMessageDialog(null,"Deleted");
                
               //rs.close();
               
           }
           else{
                JOptionPane.showMessageDialog(null,"wrong input");
           }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        }
    }//GEN-LAST:event_btnDdeleteActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        
        
        try{
           String sql="SELECT v.VehicleID,v.RegistrationNo,v.CostPerDay,v.VType,v.Model,v.Colour,v.VStatus,d.DriverID from Vehicle v ,Driver d WHERE v.VehicleID=d.VehicleID AND v.VehicleID=?";
           pst=conn.prepareStatement(sql);
           pst.setInt(1,Integer.parseInt(txtid.getText()));
           rs=pst.executeQuery();
           
           if(rs.next()){
               String a1=rs.getString(1);
               txtid.setText(a1);
               
               String a11=rs.getString(2);
               txtReg.setText(a11);
               
               String a12=rs.getString(3);
               txtCost.setText(a12);
               
               String a13=rs.getString(6);
               txtColor.setText(a13);
               
               String a2=rs.getString(4);
               txttyp.setText(a2);
               
               String a3=rs.getString(8);
              jDriver.setText(a3);
               
               String a4=rs.getString(7);
               CVehicleStatus.setSelectedItem(a4);
               
               String a5=rs.getString(5);
               txtModel.setText(a5);
               rs.close();
           }
           else 
                JOptionPane.showMessageDialog(null, "no values");
           
       }
       catch(SQLException | HeadlessException e){
           JOptionPane.showMessageDialog(null, e);
           
           
           
       }
        
    }//GEN-LAST:event_btnCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               try {
                   new Vehicle().setVisible(true);
               } catch (SQLException ex) {
                   Logger.getLogger(Vehicle.class.getName()).log(Level.SEVERE, null, ex);
               }
           }
       });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CVehicleStatus;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnDdelete;
    private javax.swing.JButton btnDinsert;
    private javax.swing.JButton btnDrefresh;
    private javax.swing.JButton btnDupdate;
    private javax.swing.JButton btnVupdate;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jDriver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggle;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtContactno;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtDid;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLicenexp;
    private javax.swing.JTextField txtLicenno;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtReg;
    private javax.swing.JTextField txtVehicleid;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtsrch;
    private javax.swing.JTextField txttyp;
    private newpackage.Validation validation1;
    // End of variables declaration//GEN-END:variables
}
